---

    - name: get python_user home-dir
      getent: database=passwd key="{{ python_user }}"


    - name: ensure ${HOME}/.virtualenv exists
      file: dest="{{ getent_passwd[python_user][4] | default('{{ ansible_env.HOME }}') }}/{{ virtualenv_dir_name | default('.virtualenv') }}"
        state=directory owner="{{ python_user }}" group="{{ python_user }}"




