---

    - include: ../../box-setup/tasks/apt-update.yml
      when: ansible_os_family == 'Debian'

    - include: ../../box-setup/tasks/yum-update.yml
      when: ansible_os_family == 'RedHat'

    - name: ensure install git
      apt: name='git-all' state=present
      when: ansible_os_family == 'Debian'

    - name: ensure install git
      yum: name='git-all' state=present
      when: ansible_os_family == 'RedHat'

    - name: ensure install python-dev
      apt: name='python-dev' state=present
      when: ansible_os_family == 'Debian'

    - name: ensure install python-devel
      yum: name='python-devel' state=present
      when: ansible_os_family == 'RedHat'

    - name: ensure install pip
      apt: name='python-pip' state=present
      when: ansible_os_family == 'Debian'

    - name: ensure install pip
      yum: name='python-pip' state=present
      when: ansible_os_family == 'RedHat'

    - name: ensure install virtualenv
      pip: name='virtualenv' state=present

    - name: get python_user home-dir
      getent: database=passwd key="{{ python_user }}"

    - name: ensure ${HOME}/.virtualenv exists
      file: dest="{{ getent_passwd[python_user][4] | default('{{ ansible_env.HOME }}') }}/{{ virtualenv_dir_name | default('.virtualenv') }}"
        state=directory owner="{{ python_user }}" group="{{ python_user }}"




