---

    - name: update apt cache
      apt: update_cache=Yes

    - name: upgrade all packages
      apt: upgrade=dist

    - name: ensure install git
      apt: name='git-all' state=present

    - name: ensure install pip
      apt: name='python-pip' state=present

    - name: ensure install virtualenv
      pip: name='virtualenv' state=present

    - name: get python_user home-dir
      getent: database=passwd key="{{ python_user }}"

    - name: ensure ${HOME}/.virtualenv exists
      file: dest="{{ getent_passwd[python_user][4] | default('{{ ansible_env.HOME }}') }}/{{ virtualenv_dir_name | default('.virtualenv') }}"
        state=directory owner="{{ python_user }}" group="{{ python_user }}"




