# input
#   - mandatory
#       * username: username to be created
#           note that the pub ssh key is pulled from git, so it should be a git username
#
#   - optional
#       * userid: uid for username, if you want to specify one
#           when not present, let it be assigned by useradd command
#
---

    - name: create group
      group: name='{{ username }}' gid='{{ userid }}' state=present
      when: userid is defined

    - name: create user
      user: name='{{ username }}' group='{{ username }}'
        uid='{{ userid }}'
        shell=/bin/bash
        state=present
      when: userid is defined

    - name: create user
      user: name='{{ username }}'
        shell=/bin/bash
        state=present
      when: userid is not defined

    - name: give sudo powers to user
      lineinfile: "dest=/etc/sudoers state=present regexp='^{{ username }}'
        line='{{ username }}   ALL=(ALL)   NOPASSWD:   ALL' validate='visudo -cf %s'"
      when: ( sudo_powers|bool )

    - name: copy ssh pub to authorized_keys
      authorized_key: user='{{ username }}' key='https://github.com/{{ username }}.keys'
      ignore_errors: Yes


