---

    - name: ensure python-dev is installed
      apt: name='python-dev' state=present

    - name: ensure python-virtualenv is installed
      apt: name='python-virtualenv' state=present

    - name: ensure python-pip is installed
      apt: name='python-pip' state=present

    - name: ensure apache is not running
      service: name='apache2' state='stopped'

    - name: ensure apache is not started at boot time
      shell: update-rc.d -f apache2 remove

    - name: ensure nginx is installed
      apt: name='nginx' state=present

    - name: ensure git is installed
      apt: name='git' state=present

    - name: ensure supervisor is installed
      apt: name='supervisor' state=present

    - name: ensure libpq-dev is installed (postgres)
      apt: name='libpq-dev' state=present

    - name: ensure libffi-dev is installed (bcrypt)
      apt: name='libffi-dev' state=present
