---

    - name: robotframework
      become_user: "{{ python_user }}"
      pip: name='robotframework' state=present
        virtualenv='{{ getent_passwd[python_user][4] | default("{{ ansible_env.HOME }}") }}/.virtualenv/{{ virtualenv_name | default("robot") }}'

    - name: Selenium2Library
      become_user: "{{ python_user }}"
      pip: name='robotframework-selenium2library' state=present
        virtualenv='{{ getent_passwd[python_user][4] | default("{{ ansible_env.HOME }}") }}/.virtualenv/{{ virtualenv_name | default("robot") }}'

    - name: XvfbRobot
      become_user: "{{ python_user }}"
      pip: name='robotframework-xvfb' state=present
        virtualenv='{{ getent_passwd[python_user][4] | default("{{ ansible_env.HOME }}") }}/.virtualenv/{{ virtualenv_name | default("robot") }}'

    - name: java 1.7 (for selenium)
      become: True
      apt: name='{{ item }}' state=present
      with_items:
        - openjdk-7-jdk
        - openjdk-7-jre
        - openjdk-7-dbg
        - openjdk-7-doc

    - name: xvfb (headless browser)
      become: True
      apt: name='xvfb' state=present

    - name: firefox
      become: True
      apt: name='firefox' state=present




