---


- hosts: all
  remote_user: "{{ r_user | default('vagrant') }}"
  become: yes
  vars:
    devo_username: "nmaekawa"
    devo_userid: 2132

  roles:
    - role: box-setup

    - role: user-management
      set_env_for_username: True
      username: "{{ devo_username }}"
      userid: "{{ devo_userid }}"

    - role: python
      python_user: "{{ devo_username }}"

    - role: robotframework
      python_user: "{{ devo_username }}"

    - role: znzj.rbenv
      rbenv_ruby_version: 2.2.3



