---


- hosts: all
  remote_user: "{{ r_user | default('vagrant') }}"
  become: yes

  roles:
    - role: box-setup

    - role: user-management
      set_env_for_username: True
      username: "nmaekawa"
      userid: 2123
      sudo_powers: True

    - role: python
      python_user: "nmaekawa"

    - role: ansible
      python_user: "nmaekawa"

    - role: robotframework
      python_user: "nmaekawa"

